global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9091"]

  - job_name: "cassandra"
    static_configs:
      - targets: ["localhost:9042"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "spark"
    static_configs:
      - targets: ["spark-master:4040", "spark-worker:4041"]

  - job_name: "kafka"
    static_configs:
      - targets: ["broker:29092"]
